# Generated by Django 3.1.7 on 2021-03-26 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blackpinkinfo', '0002_auto_20210326_0430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='prize',
        ),
        migrations.AddField(
            model_name='prize',
            name='song',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blackpinkinfo.song'),
        ),
    ]
